# Generated by Django 4.1.7 on 2023-05-05 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student_register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('mobile', models.CharField(max_length=200)),
                ('dob', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=200)),
                ('relegion', models.CharField(max_length=200)),
                ('adhar', models.ImageField(max_length=200, upload_to='')),
                ('photo', models.ImageField(max_length=200, upload_to='')),
                ('address', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('pincode', models.IntegerField(null=True)),
                ('guardianname', models.CharField(max_length=200)),
                ('guardianmobile', models.IntegerField()),
                ('sslccertificate', models.ImageField(max_length=200, upload_to='')),
                ('sslcpassoutyear', models.IntegerField()),
                ('schoolname', models.CharField(max_length=200)),
                ('schoollocation', models.CharField(max_length=200)),
                ('hss_name', models.CharField(max_length=200)),
                ('hsscertificate', models.ImageField(max_length=200, upload_to='')),
                ('hsspersentage', models.IntegerField()),
                ('hsspassoutyear', models.IntegerField()),
            ],
        ),
    ]
