# Generated by Django 4.1.7 on 2023-05-05 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_alter_student_register_pincode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_register',
            name='pincode',
            field=models.IntegerField(null=True),
        ),
    ]
